### ISSUE TITLE
Uncaught ReferenceError: webpackJsonp

### ISSUE THREAD

**Issue by michaellouieloria** [gpbl/isomorphic500#14]
I'm getting an error when using production as environment mode in windows 8

I've followed the instructions
gulp build
set NODE_ENV=production
node build/app.js

"Uncaught ReferenceError: webpackJsonp is not defined" is displayed in the console

**Comment by gpbl** [comment]
I'm closing this because is not anymore relevant with the new version. @michaellouieloria would you give a try with the updated app?
