### ISSUE TITLE
Next steps for this project

### ISSUE THREAD

**Issue by gpbl** [gpbl/isomorphic500#19]
During the last months I've learnt lot of things I'd like to apply to this project, which is starting to get outdated. Instead of a "template", it could became a work-in-progress, full-stack example for people approaching an isomorphic app with React and Flux.

The critical parts I would explore are the architecture design and the development environment:

**Architecture**

- isomorphic flux architecture (with fluxible)
- smart and dumb React components ([inspiration](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0)) 
- atomic, per-component CSS files
- an approach to i18n with react-intl
- use of immutable data (immutable.js)

**Dev environment**

- use of babeljs and eslint 
- no build process (skip gulp)
- a solid webpack config (e.g. assets)
- components and styles with live reloading
- use webpack to compile server-side as well
- tests with Jest 

There’s a lot to do! 
I need to find an example app that is not as boring as a to-do list or a repo browser. The problem is that it’s hard to find public or freely available API exposing enough data...
... so I thought to make a 500px client (because I love photography), and call this project **isomorphic 500**. 

Let see where it goes… I'd appreciate some feedback and contributions. I've added [a gitter chat](https://gitter.im/gpbl/isomorphic-react-template).

I'm happy this project got so many stargazers :-) Thanks to all!

**Comment by vesparny** [comment]
@gpbl I'm trying to do something similar, just set the project up.
https://github.com/vesparny/react-jwt-example/

**Comment by corydolphin** [comment]
The main thing I believe this project lacks is actually sending shared state between the client and the server.

Practically, many applications wish to fetch data via some internal or external API. The hard part of isomorphism in my experience is figuring out how to share the 'right' state between the server and client, and piping that over the wire.

**Comment by gpbl** [comment]
@corydolphin you are right – that's covered very well by fluxible.

**Comment by gpbl** [comment]
I've changed the name of the project to "isomorphic500" – it fits better! I've already implemented quite all the goals I set, beside the tests where i need to experiment a bit more...

**Comment by iam4x** [comment]
:clap: Impressed!
