### ISSUE TITLE
SASS recompilation doesn't work

### ISSUE THREAD

**Issue by romanenko** [gpbl/isomorphic500#21]
I'm starting with a clean project.

    $ git clone https://github.com/gpbl/isomorphic-react-template.git
    Cloning into 'isomorphic-react-template'...
    ....
    Resolving deltas: 100% (767/767), done.
    Checking connectivity... done.
    $ cd isomorphic-react-template
    $ npm install
 
Then I do `npm start` and the development server starts. Then, I modify `style/main.scss` and server logs:

    app Changed main.scss +21s

But no changes happen in `public/css/main.css`. What can be wrong? I tried to replace `sass.render` with `sass.renderSync` in `dev-tools.js` but with no success.

I'm using node v0.12.1 running on OSX 10.10.2

**Comment by gpbl** [comment]
I'm closing this because is not relevant anymore with the last version. @romanenko did you solve your problem, btw?
