### ISSUE TITLE
404 Not Found and 500 Server error routes

### ISSUE THREAD

**Issue by gpbl** [gpbl/isomorphic500#3]
For the not found page:

- [x] NotFound Route
- [x] 404 Status on server

For the error page:

- [x] Load the error view with express

**Comment by steida** [comment]
You don't need lodash :-p
```
let isNotFound = state.routes.some(route => route.name == 'not-found')
```

**Comment by Snegostoop** [comment]
Hi @gpbl, 
I'm struggling with a similar situation as you described in https://github.com/rackt/react-router/issues/458#issuecomment-64838487
I have a condition in ParentComponent#render() which renders NotFound component if resource hasn't been found.

In this case I can't spot it this way
```
Router.run(routes, req.url, (Handler, state) => {
       const html = React.renderToString //.....
       const isNotFound = _.find(state.routes, { 'name': 'not-found' });
       res.status(isNotFound ? 404 : 200).send(html);
```
because in state.routes I still have the route of ParentComponent and not 'not-found'.
Please suggest how to do that if you have figured it out. Thanks.

**Comment by gpbl** [comment]
I'm closing this because it becomes obsolete with the recent 'isomorphic500' release, based on flux. At the end I switched to the fluxible's router: it made easier to manage the error pages  – mainly because it keeps all inside a "flux" flow.

@Snegostoop did you find a solution with the suggestions you got in the react-router comments?

**Comment by Snegostoop** [comment]
No, but I elaborated the question as much as I could so I hope we'll at least find out if it's even possible.
I'm also developing my app using flux, but I use another isomorphic-friendly library - flummox. Thanks for your suggestion of fluxible, I'll consider moving to it if this issue with react-router will not resolve.

**Comment by gpbl** [comment]
@Snegostoop I understand better now – you are in the case where a NotFound route may come from a 404 API response (e.g. /user/:id when `id` is a not existing user). In a flux application having a RouteStore, the idea (proposed by the fluxible team) is to execute an action that tell the store to display a 404 page. Honestly I don't know how this could work in a `Router.run` callback.
