### ISSUE TITLE
Warning in browser console.

### ISSUE THREAD

**Issue by herve1976** [gpbl/isomorphic500#38]
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) xgk2kmbk.2.0.1.0">isasdadhic500</strong>
 (server) xgk2kmbk.2.0.1.0">isomorphic500</strong>

Any idea what this warning is about? Am I the only to get this warning?

Cordially,

Hervé

**Comment by gpbl** [comment]
@herve1976 Could you search for `isasdadhic` in your code base or try to restart the node server? The page generated by node has a string different from that mounted on the browser.

**Comment by herve1976** [comment]
Issue Fixed. Grazie Mille.
