### ISSUE TITLE
isomorphic500 Intl is not supported, so the polyfill has been loaded

### ISSUE THREAD

**Issue by herve1976** [gpbl/isomorphic500#39]
When I run:
$ npm run dev

> isomorphic500@2.0.0 dev /Users/herve76/Desktop/isomorphic500
> NODE_ENV=development DEBUG=isomorphic500 node index
  isomorphic500 Intl is not supported, so the polyfill has been loaded. +0ms
Express development server listening on 3000
  isomorphic500 Webpack development server listening on localhost:3001 +2s
Hash: 28498d7b5b156072b02c
Version: webpack 1.8.11
Time: 7796ms

Why does it say that isomorphic500 Intl is not supported?

Cordially,

Hervé

**Comment by gpbl** [comment]
We load a polyfill to support `Intl` on node: https://github.com/gpbl/isomorphic500#the-difficult-parts
