### ISSUE TITLE
Switching from the server side rendering to the client side for debugging purpose

### ISSUE THREAD

**Issue by haohcraft** [gpbl/isomorphic500#45]
Where there is some js error on the pages/xxxPage.js, the error will be throwing in the terminal which is my server side.

So I am wondering if it is possible to switch the project from the server side to the client server on dev. And How?
Thanks.

**Comment by gpbl** [comment]
Hi @haohcraft, maybe you are looking for something like [node-inspector](https://github.com/node-inspector/node-inspector)?
