### ISSUE TITLE
Problems on Windows

### ISSUE THREAD

**Issue by Wolfeitz** [gpbl/isomorphic500#47]
First attempt at running on Windows resulted in:
--------------------------------------
D:\Projects\isomorphic500>npm run dev
> isomorphic500@2.0.0 dev D:\Projects\isomorphic500
> NODE_ENV=development DEBUG=isomorphic500 node index
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
--------------------------------------

I edited the package.json file to comment out the dev string
-> "dev": "", //NODE_ENV=development DEBUG=isomorphic500 node index

Then ran 3 separate lines in the command prompt
SET NODE_ENV=development
SET DEBUG=isomorphic500
node index

Things appeared to run better but my web page at that point said simply "Something bad happened".

I'm not sure how to go about fixing this error.
--------------------------------------
D:\Projects\isomorphic500>node index
Express development  server listening on 3000
  isomorphic500 Detected locale (from browser) is en +0ms
Error on request GET /
[TypeError: Cannot read property 'script' of undefined]
TypeError: Cannot read property 'script' of undefined
    at renderApp (D:/Projects/isomorphic500/src/server/render.js:48:29)
    at D:/Projects/isomorphic500/src/server/render.js:76:19
GET / 500 65.799 ms - 22
  isomorphic500 Detected locale (from browser) is en +5s
Error on request GET /
[TypeError: Cannot read property 'script' of undefined]
TypeError: Cannot read property 'script' of undefined
    at renderApp (D:/Projects/isomorphic500/src/server/render.js:48:29)
    at D:/Projects/isomorphic500/src/server/render.js:76:19
GET / 500 25.604 ms - 22
GET /favicon.ico 200 9.114 ms - -
^C
--------------------------------------

**Comment by gpbl** [comment]
Hi @Wolfeitz, yours seems the same problem described here: https://github.com/gpbl/isomorphic500/issues/40

Please see if it helps, thanks!
