### ISSUE TITLE
Use ES6 in webpack prod config

### ISSUE THREAD

**Issue by rafayepes** [gpbl/isomorphic500#49]
It is confusing to see the dev config in ES6, like all the code and then the prod config in ES5.

Any particular reason for that?

**Comment by gpbl** [comment]
Yes: I couldn't find a way to pass to the webpack bin (used by the `npm run build` script) a config written in ES6. On dev we don't use the bin so we require the config in a node.js script, after `babel/register` hook has been installed. Anyway it's a good point, going to ask on the webpack's gitter chat...

**Comment by rafayepes** [comment]
What about doing something similar to here?

https://github.com/gpbl/isomorphic500/blob/31e91c650c4b99d91424ecbef6e13531ab50e9a1/src/config.js

and load babel/register in this config?

**Comment by gpbl** [comment]
Yes I was thinking to that option, but perhaps keeping the config (and /webpack/utils) in ES5 would be a better compromise.

**Comment by rafayepes** [comment]
Yeah. Maybe just less tricky and it will be more consistent that having one
config in ES6 and another in ES5.
