### ISSUE TITLE
Add nodemon to reload server when server files change?

### ISSUE THREAD

**Issue by robink** [gpbl/isomorphic500#53]
I'm currently using nodemon to restart the app when one of the server's file is changing, like `server.js` or any files under `src/server`. What about including it in this repo?

**Comment by gpbl** [comment]
If you have a good nodemon config to share I'd love to include it in the project. The last time I tried, it didn't play well with the webpack's hot reload. Please send a PR if you don't mind!

**Comment by robink** [comment]
Will do !

**Comment by gpbl** [comment]
Thanks! This has been fixed with #56
