### ISSUE TITLE
authentication

### ISSUE THREAD

**Issue by ssmlee04** [gpbl/isomorphic500#57]
I have a backend nodejs/express server running and I want to do authentication.  Once POST to /login I will retrieve a response header which contains a token for my future API calls.  In the future whenever I click on other routes I just GET /loggein for updated user info.

This is OK if I don't refresh the browser and the information will be stored in the context.   But when the user refreshs the browser the context is lost and user will forever lose this login token so he has to login again.  

So I am wondering if there's a recommended login / profile retrieval process?  I am doing something like this for now: 

    context.dispatch(Actions.LOGIN_SUCCESS, {
          user: data.body.user, 
          token: data.header.token
    });

Or should I use localStorage?  It seems extremely stupid to put validation token inside a localStorage...?  
Thanks.

**Comment by gpbl** [comment]
Yup, if you need to keep the authentication when refreshing the page (or when the user comes back), you want to save the authentication token somewhere, usually in a cookie. 

In your express app, after the login, save the cookie with the token. Your next `GET`s to `/login` should check `req.cookies` to verify the token against your authentication system.

**Comment by ssmlee04** [comment]
ok I see this info in req.cookies. I'll try to pass into into all future request I guess that's it thanks!
btw.... how do I extract email / password from the forms and pass them into actions?  I am currently using jquery but this seems weird..

**Comment by gpbl** [comment]
@ssmlee04 if you don't mind, there's a gitter chat for this repo: https://gitter.im/gpbl/isomorphic500
This is a better place to talk with other developers and ask questions :)

**Comment by ssmlee04** [comment]
yes that's a great idea.  I'll go over there an take a look.  Thanks a lot for your info and help!
