### ISSUE TITLE
Windows 8 Install won't run (development)

### ISSUE THREAD

**Issue by codeuniquely** [gpbl/isomorphic500#58]
I installed node v0.12.(0.12.4)
I cloned your project
npm install (run as administrator) 

install produced some errors (actually lots of them) - but here is an example

    F:\Projects\isomorphic500-master\node_modules\webpack-dev-server\node_modules\socket.io-lient\node_modules\engine.io-client\node_modules\ws>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
      else (rebuild)Building the projects in this solution one at a time. 
      To enable parallel build, please add the "/m" switch.
      bufferutil.cc
    F:\Projects\isomorphic500-master\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(213): error C2039: 'ThrowException' : is not a member of 'v8' [F:\Projects\isomorphic500-master\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\isomorphic500-master\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(213): error C2039: 'New' : is not a member of 'v8::String' [F:\Projects\isomorphic500-master\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
      C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
    F:\Projects\isomorphic500-master\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(213): error C3861: 'ThrowException': identifier not found [F:\Projects\isomorphic500-master\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\isomorphic500-master\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(213): error C3861: 'New': identifier not found [F:\Projects\isomorphic500-master\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\isomorphic500-master\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(218): error C2039: 'ThrowException' : is not a member of 'v8' [F:\Projects\isomorphic500-master\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\isomorphic500-master\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(218): error C3861: 'ThrowException': identifier not found [F:\Projects\isomorphic500-master\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\isomorphic500-master\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(222): error C2039: 'New' : is not a member of 'v8::String' [F:\Projects\isomorphic500-master\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
      C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'

The post install build process ran with a few warnings

     > isomorphic500@2.0.0 build F:\Projects\isomorphic500-master
     > webpack --stats --progress --config ./webpack/prod.config.js

     42% 98/179 build modulesAutoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
     43% 99/179 build modulesAutoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
     52% 179/251 build modulesAutoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
     56% 197/256 build modulesAutoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
     56% 198/256 build modulesAutoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
     56% 199/256 build modulesAutoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
     56% 200/256 build modulesAutoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
     65% 251/269 build modulesAutoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
     66% 301/318 build modulesAutoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
     65% 317/344 build modulesAutoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
     68% 405/415 build modulesAutoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
     68% 406/415 build modulesAutoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
     68% 407/415 build modulesAutoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
     68% 408/415 build modulesAutoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
     69% 409/415 build modulesAutoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
     69% 410/415 build modulesAutoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
     69% 411/415 build modulesAutoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
     69% 412/415 build modulesAutoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
     69% 413/415 build modulesAutoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
     69% 414/415 build modulesAutoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
    Hash: 93d9b22a32b415831dbe
    Version: webpack 1.9.10
    Time: 58250ms

                        Asset                            Size      Chunks           Chunk Names
         main-159534d8036482e126a4.css                  5.74 kB       0  [emitted]  main
         3fcabfc9ec25aababcdaa2b056cf32bf.svg           2.05 kB          [emitted]
         locale-it-abbb4c01f9add2390a1f.js              14.8 kB    1, 2  [emitted]  locale-it
         locale-it-no-intl-4377e1ebae56b2bae973.js      1.55 kB       2  [emitted]  locale-it-no-intl
         locale-en-4179b1a80b22685aea97.js              13.4 kB       3  [emitted]  locale-en
         intl-bb08eeb1f614b9790298.js                   27.5 kB       4  [emitted]  intl
         main-159534d8036482e126a4.js                    390 kB       0  [emitted]  main
         main-159534d8036482e126a4.js.map               4.16 MB       0  [emitted]  main
         main-159534d8036482e126a4.css.map               106 bytes    0  [emitted]  main
         locale-it-abbb4c01f9add2390a1f.js.map          37.5 kB    1, 2  [emitted]  locale-it
         locale-it-no-intl-4377e1ebae56b2bae973.js.map   5.7 kB       2  [emitted]  locale-it-no-intl
         locale-en-4179b1a80b22685aea97.js.map          32.4 kB       3  [emitted]  locale-en
         intl-bb08eeb1f614b9790298.js.map                310 kB       4  [emitted]  intl

but nothing else seemed to be an issue so I assumed as the build has run it was OK.

    npm start dev 

produced an error of isomorphic500@2.0.0 start: `NODE_ENV=production node index "dev"`

so I did it all manually

    SET NODE_ENV=development 
    SET DEBUG=isomorphic500
    node index

I get the message.

    Express development  server listening on 3000

I navigated to that address

    http://localhost:3000

Node now throws an error into the console

      isomorphic500 Detected locale (from browser) is en +0ms
    Error on request GET /
    [TypeError: Cannot read property 'script' of undefined]
    TypeError: Cannot read property 'script' of undefined
        at renderApp (F:/Projects/isomorphic500-master/src/server/render.js:48:29)
        at F:/Projects/isomorphic500-master/src/server/render.js:76:19
    GET / 500 293.241 ms - 22

The browser just displays a blank page with:

    Something bad happened

however, when I run 

    SET NODE_ENV=production
    SET DEBUG=
    node index

everything seem to work correctly. There appears to be some issue in the development configuration.

**Comment by Todilo** [comment]
see @davidgilbertson at https://github.com/gpbl/isomorphic500/issues/40
I did write
SET NODE_ENV=development
first then changed the package.json and the run with:
npm run dev

and it worked.

**Comment by codeuniquely** [comment]
OK - then closed...
