### ISSUE TITLE
Error Cannot use [chunkhash] on "npm run dev"

### ISSUE THREAD

**Issue by cmrcmr** [gpbl/isomorphic500#61]
I ran the following commands
git clone https://github.com/gpbl/isomorphic500.git
cd isomorphic500
npm install

But I get this error when I run
npm run dev

[name]-[chunkhash].js
Cannot use [chunkhash] for chunk in '[name]-[chunkhash].js' (use [hash] instead)
Error: Cannot use [chunkhash] for chunk in '[name]-[chunkhash].js' (use [hash] instead)

**Comment by gpbl** [comment]
Oh thanks for this! It seems [an issue](https://github.com/webpack/webpack/issues/358) introduced with a recent webpack version. Update coming soon...
