### ISSUE TITLE
Service set up with onSave reload

### ISSUE THREAD

**Issue by jhwang09** [gpbl/isomorphic500#64]
Hi,

I really like how you set up your app and I am very much following how you set up the app.

I do have one question though:

When you are doing development and when you save files (server side code), does the app restart for you? It works great for all the client side work, but it doesn't reload node server when I save files for server side code.

Could you point me to how I achieve that? 

Sorry, this is not really issues, but I would appreciate your help!

**Comment by gpbl** [comment]
Hi @jhwang09 thanks ! Actually, the server restarts when you save server-only data with `nodemon` (not the best solution, yet). In which case you don't see the changes being applied?
