### ISSUE TITLE
webpack/write-stats.js

### ISSUE THREAD

**Issue by halt-hammerzeit** [gpbl/isomorphic500#76]
FYI
https://github.com/halt-hammerzeit/webpack-isomorphic-tools

(closing since you've got the notification)

**Comment by gpbl** [comment]
Thanks @halt-hammerzeit ! I'm not sure I understand what is your module doing... Have you considered to compile server-side JavaScript with webpack?

**Comment by halt-hammerzeit** [comment]
@gpbl oh, sorry, I thought your project used image requiring. Seems it doesn't. Cheers

**Comment by gpbl** [comment]
well i'm actually considering to improve that part: new ideas are always welcome 👍
