### ISSUE TITLE
Routing help to new page on click

### ISSUE THREAD

**Issue by sathify** [gpbl/isomorphic500#80]
I'm trying to show a list of users in a search page similar to photos and then onClick trying to route them to individual user page. But the props is an `{}` and `props.id` does not exist in the below code. 
```
EmployeePage = connectToStores(EmployeePage, [UserStore], (context, props) => ({
    user: context.getStore(UserStore).get(props.id)
}));

```
Would love to know how in [PhotosPage](https://github.com/gpbl/isomorphic500/blob/master/src/pages/PhotoPage.js#L7) the props is getting passed in.

I'm doing the same things as this application like [triggering action](https://github.com/gpbl/isomorphic500/blob/master/src/pages/InitActions.js#L12) and other things. I'm new to react/fluxible and a little confused so much appreciate help.

**Comment by gpbl** [comment]
Hi @sathify, `connectToStore` knows the props you are passing to its wrapped component, and make them available in the `(context, props) => {}` function so you can use them.

In the case of a Page component, as `EmployeePage` or `PhotosPage`, you are not actually rendering this component directly. Instead, it is available as the `currentRoute` prop [in Application.js](https://github.com/gpbl/isomorphic500/blob/master/src/Application.js#L65). You tell the router about this component in the `handler` [route config](https://github.com/gpbl/isomorphic500/blob/master/src/routes.js#L28).

`PhotosPage` needs a `featured` prop, and likely your `EmployeePage` needs an `id` prop. 

In the case of the PhotosPage route handler, the value of this prop is a URL token, e.g. the `:featured` param in [its route](https://github.com/gpbl/isomorphic500/blob/master/src/routes.js#L19).

The router knows about the value of such params and we use them in Application.js:
https://github.com/gpbl/isomorphic500/blob/master/src/Application.js#L88-L92
```js
const params = currentRoute.get("params").toJS();
content = <Handler {...params} />;
```

There, when the router matches a `/photos/:featured` route, such as `/photos/upcoming`, the `Handler` is the `PhotosPage` component and the `params` are `{featured: "upcoming"}`:

```js
// Application.js when matching /featured/:feature route
const params = currentRoute.get("params").toJS();  //  {featured: "upcoming"}
content = <PhotosPage featured="upcoming" />;     // this is the content actually rendered

// PhotosPage component
PhotosPage = connectToStores(PhotosPage, [PhotosStore], (context, props) => ({
    // now props is {featured: "upcoming"}
    photos: context.getStore(PhotosStore).get(props.featured)
}));
```

So if you are missing the params in the `connectToStore` callback, you likely did not configure the route to accept that params, or you are doing something wrong in your Application.js. Debug the `render` method in Application.js to check the value of `params`.

**Comment by sathify** [comment]
@gpbl Thanks much for your valuable pointers and clear explanation. Makes total sense, I did not configure the route to parse routing params and send in to ```<Handler {...params}>```. Much appreciated.

**Comment by sathify** [comment]
@gpbl I have a DataService issue when I try to use the create method from the service. I also tried using a postman client to verify and I get the same error so not sure what is going on. The read method works fine. My service looks similar to [this](https://github.com/porchdotcom/isomorphic-porch-demo/blob/master/server/services/project-service.js). Very much appreciate any valuable pointers on the issue when you have time. 

```
HttpError
   at Object.<anonymous> (/Users/satheesh/dev/rackudos/node_modules/fluxible-plugin-fetchr/node_modules/fetchr/node_modules/fumble/HttpError.js:28:23)
   at Module._compile (module.js:456:26)
   at Module._extensions..js (module.js:474:10)
   at Object.require.extensions.(anonymous function) [as .js] (/Users/satheesh/dev/rackudos/node_modules/babel-core/lib/api/register/node.js:214:7)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous> (/Users/satheesh/dev/rackudos/node_modules/fluxible-plugin-fetchr/node_modules/fetchr/node_modules/fumble/libs/fumble.http.js:8:17)
   at Module._compile (module.js:456:26)
```
