### ISSUE TITLE
SEO multi Language perspective

### ISSUE THREAD

**Issue by maiopirata** [gpbl/isomorphic500#87]
From a SEO perspective the ideal solution for multi language/multi region url should be using sub-folders.

I'm starting to think about it but I kind of lost! I would like that the route:
http://isomorphic500.herokuapp.com/featured/fresh_yesterday
will be linked to 
http://isomorphic500.herokuapp.com/it/featured/ieri for example

From the Html Document point of view it easy to change the title and the description meta tag to take an international message.

For achieving multi language routes it seams a bit tricky to me.

This is becoming a huge problem for me in production, since google is seeing my english website...

**Comment by maiopirata** [comment]
I try to be more clear on what I would like to achieve:

the route: "/folderEN/pageEN
should be replicated in different languages like
IT: "it/folderIT/pageIT"

but that's not all.. 
1) The meta data for the page should be created in many languages. This is fine since the RouteStore can give the route handler name, and so one can pick the international message.
2) The pages in other languages have to be linked to the main page using the meta tags for that:
<link rel="alternate" hreflang="it" href="http://example.com/it/folderIT/pageIT" />
<link rel="alternate" hreflang="x" href="http://example.com/folderEN/pageEN" />

Why this should bother us?
https://moz.com/blog/subdomains-vs-subfolders-rel-canonical-vs-301-how-to-structure-links-optimally-for-seo-whiteboard-friday

I hope that someone can give me a hint...

**Comment by maiopirata** [comment]
Ok,
as explained here: https://github.com/yahoo/fluxible-router/issues/50

in fluxible-router one should simply put:

    {
        page: {
            method: 'GET',
            path: '/:lang([a-z]{2})?/page1',
            handler: require('../components/Page.jsx'),
            action: require('../actions/loadPage')
        }
    }

and then the loadPage action should set the default lang for the page,
but how to link the corresponding pages in other languages.

I guess it should be done also in the loadPage action..

**Comment by gpbl** [comment]
Ehy @maiopirata, for a better path matching use something like this:

```js
const locales = ["en", "it"];
page = {
   path: `/:lang(${locales.join("|")})` // match only /en or /it, otherwise 404
}
```

If you want to localize the url, it really depends from what you want to do. For example, this path:

```js
let path =  `/:lang(${locales.join("|")})/featured/:feature`
```

will match any "feature" string coming after `/featured/`. If you want to catch `/it/featured/ieri`, then your params will be `{ lang: "it", feature: "ieri" }`. In the page action, do something for matching "ieri" with the actual feature the server wants (i.e. "fresh_yesterday") and you are done.

**Comment by maiopirata** [comment]
thank @gpbl!

I think it is ok. I will use a wrapper component that use the page action to match the route.
I could also use the same logic to obtain the links of the same page in the other languages!
